spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: xycservicecloud-config-xyc-dev
---
spring:
  profiles: test
  application:
    name: xycservicecloud-config-xyc-test